### ISSUE TITLE
static member variables

### ISSUE THREAD

**Issue by bradbell** [CSCsw/ColPack#27]
Reference:
https://en.cppreference.com/w/cpp/language/static

There are static member variables in 
https://github.com/CSCsw/ColPack/blob/master/src/SMPGC/SMPGC.h
That do not have a declaration outside the class.

This leads to undefined externals; e.g.,
libColPack.so.0: undefined reference to `SMPGC::RAND_SEED'

This particular error can be fixed by adding 
const int SMPGC::RAND_SEED;
at the end of
https://github.com/CSCsw/ColPack/blob/master/src/SMPGC/SMPGC.cpp

**Comment by CSCsw** [comment]
Thanks @bradbell . 
You are right, we should adding `const int SMPGC::RAND_SEED` in the cpp file.
It should be fixed soon.
